Fix not ignoring missing for pluralization
glebm/i18n-tasks pull request #389
Opened 2021-09-03 17:45 UTC by pedrozath

When you add a pattern for ignoring missing, it is currently not ignoring the pluralization for that pattern.

This commit fixes that, by skipping plural nodes that were ignored in the configuration for `ignore_missing`.

2021-09-03 18:25 UTC, yorsant commented
References #331

2021-09-03 21:45 UTC, glebm requested changes
Can you please also add or update the test for this?

2021-09-03 21:45 UTC, glebm commented on lib/i18n/tasks/missing_keys.rb
> +          next if ignore_key?(node.key_names.first, :missing)
```suggestion
          next if ignore_key?(node.full_key(root: false), :missing)
```

2021-09-07 14:46 UTC, pedrozath commented
@glebm thanks for the reviewing this! just updated the test :)

2021-09-10 04:45 UTC, merged